### ISSUE TITLE
Settings target settings doesn't seem to work.

### ISSUE THREAD

**Issue by daenuprobst** [lavrton/sublime-better-typescript#11]
Configuration in TypeScript.sublime-settings:
"target": "ES5"
Error on compilation:
Accessors are only available when targeting ECMAScript 5 and higher

I am the only one with this problem?

**Comment by awijnen** [comment]
just spent way to long trying to get this to work, even though it's trivial. Here's what you should do:

In your build configuration file (see README for how to make / what to but in there) you should add some command options to let the typescript compiler (the npm typescript package) know you want to target ES5 (as opposed to the default ES3).

The configuration file should be:
{
    "cmd": ["tsc", "-d", "-m", "amd", "--sourcemap", "--target",  "ES5", "$file"],
    "file_regex": "(.*\\.ts?)\\s\\(([0-9]+)\\,([0-9]+)\\)\\:\\s(...*?)$",
    "selector": "source.ts",
    "osx": {
       "path": "/usr/local/bin:/opt/local/bin"
    },
    "windows": {
        "cmd": ["tsc.cmd", "-d", "-m", "amd", "--sourcemap", "$file"]
    }
}

The **"--target",  "ES5"** is what's different from the instructions in the README
